defaults:
  - base: base
  - data@data0: ecg_heedb_S0001-1987
  - data@data1: ecg_heedb_S0001-1988
  - data@data2: ecg_heedb_S0001-1994
  - data@data3: ecg_heedb_S0001-2006
  - data@data4: ecg_heedb_S0001-2007
  - data@data5: ecg_heedb_S0001-2011
  - data@data6: ecg_heedb_S0001-2013
  - data@data7: ecg_heedb_S0001-2015
  - data@data8: ecg_heedb_S0001-2016
  - data@data9: ecg_heedb_S0001-2017
  - data@data10: ecg_heedb_S0001-2018
  - data@data11: ecg_heedb_S0001-2019
  - data@data12: ecg_heedb_S0001-2020
  - data@data13: ecg_heedb_S0001-2021
  - data@data14: ecg_heedb_S0002-1993
  - data@data15: ecg_heedb_S0002-1997
  - data@data16: ecg_heedb_S0002-1998
  - data@data17: ecg_heedb_S0002-2000
  - data@data18: ecg_heedb_S0002-2003
  - data@data19: ecg_heedb_S0002-2004
  - data@data20: ecg_heedb_S0002-2008
  - data@data21: ecg_heedb_S0002-2009
  - data@data22: ecg_heedb_S0002-2013
  - data@data23: ecg_heedb_S0002-2015
  - data@data24: ecg_heedb_S0002-2016
  - data@data25: ecg_heedb_S0002-2018
  - data@data26: ecg_heedb_S0002-2020
  - data@data27: ecg_heedb_S0002-2022
  - data@data28: ecg_heedb_S0003-1990
  - data@data29: ecg_heedb_S0003-1994
  - data@data30: ecg_heedb_S0003-2009
  - data@data31: ecg_heedb_S0003-2010
  - data@data32: ecg_heedb_S0003-2013
  - data@data33: ecg_heedb_S0004-2019
  - data@data34: ecg_heedb_emory_2010
  - data@data35: ecg_heedb_emory_2011
  - data@data36: ecg_heedb_emory_2012
  - data@data37: ecg_heedb_emory_2013
  - data@data38: ecg_heedb_emory_2014
  - data@data39: ecg_heedb_emory_2015
  - data@data40: ecg_heedb_emory_2016
  - data@data41: ecg_heedb_emory_2017
  - data@data42: ecg_heedb_emory_2018
  - data@data43: ecg_code15
  - ts: tsenc
  - ts/enc: rnn
  - ts/pred: s4
  - ts/head: mlp
  - ts/head_ssl: s4
  - ts/loss: jepa
  - ts/mask: jepa_multi_block_mask
  - ts/ema: jepa
  - static: none
  - head: none
  - loss: none
  - trainer: trainer
  - task: ecg
  - metric: none
  - _self_

data0:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data1:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data2:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data3:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data4:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data5:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data6:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data7:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data8:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data9:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data10:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data11:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data12:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data13:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data14:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data15:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data16:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data17:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data18:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data19:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data20:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data21:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data22:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data23:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data24:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data25:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data26:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data27:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data28:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data29:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data30:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data31:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data32:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data33:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data34:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data35:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data36:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data37:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data38:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data39:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data40:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data41:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data42:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []
data43:
  train_fold_ids: ["xm1"]
  val_fold_ids: ["m1"]
  test_fold_ids: []

base:
  optimizer: "adam"
  lr: [3e-3]
  weight_decay: 1e-3
  batch_size: 64
  fs: 240.
  input_channels: 12
  input_size: 2.5

trainer:
  gpus: 1
  refresh_rate: 1
  username: "user"
  epochs: 10
  precision: 32

ts:
  enc:
    features: [ 512, 512, 512, 512 ]
    kss: [ 3, 1, 1, 1 ]
    strides: [ 2, 1, 1, 1 ]
    dilations: [1, 1, 1, 1]
    normalization: true
    layer_norm: false
  pred:
    causal: false
    state_dim: 8
    model_dim: 512
    backbone: "s42"
    layers: 4
    dropout: 0.2
    prenorm: false
    batchnorm: false
  head_ssl:
    n_layers: 1
    causal: false
    d_model: -1
  ema:
    average_top_k_layers: 1
    layer_norm_targets: true
    instance_norm_targets: false
    normalize_targets: true
  mask:
    enc_mask_scale: [0.85, 1.0]
    pred_mask_scale: [0.15, 0.20]
    nenc: 1
    npred: 4
    min_keep: 64
    allow_overlap: false
  loss:
    loss_fn_type: "smooth_l1"
    beta: 1.0

